/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ICustomArrowLeft: typeof import('~icons/custom/arrow-left')['default']
    ICustomArrowRight: typeof import('~icons/custom/arrow-right')['default']
    ICustomCheck: typeof import('~icons/custom/check')['default']
    ICustomChevronVertical: typeof import('~icons/custom/chevron-vertical')['default']
    ICustomEllipsis: typeof import('~icons/custom/ellipsis')['default']
    ICustomLogo: typeof import('~icons/custom/logo')['default']
    ICustomMinus: typeof import('~icons/custom/minus')['default']
    ICustomPanelLeft: typeof import('~icons/custom/panel-left')['default']
    ICustomPlay: typeof import('~icons/custom/play')['default']
    ICustomPlus: typeof import('~icons/custom/plus')['default']
    ICustomSettings: typeof import('~icons/custom/settings')['default']
    ICustomStepBack: typeof import('~icons/custom/step-back')['default']
    ICustomStepForward: typeof import('~icons/custom/step-forward')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
