/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrowLeft: typeof import('./src/01_app/assets/icons/arrow-left.svg')['default']
    ArrowRight: typeof import('./src/01_app/assets/icons/arrow-right.svg')['default']
    Check: typeof import('./src/01_app/assets/icons/check.svg')['default']
    ChevronDown: typeof import('./src/01_app/assets/icons/chevron-down.svg')['default']
    ChevronUp: typeof import('./src/01_app/assets/icons/chevron-up.svg')['default']
    Close: typeof import('./src/01_app/assets/icons/close.svg')['default']
    Compass: typeof import('./src/01_app/assets/icons/compass.svg')['default']
    Docs: typeof import('./src/01_app/assets/icons/docs.svg')['default']
    Ellipsis: typeof import('./src/01_app/assets/icons/ellipsis.svg')['default']
    Home: typeof import('./src/01_app/assets/icons/home.svg')['default']
    ICustomArrowLeft: typeof import('~icons/custom/arrow-left')['default']
    ICustomArrowRight: typeof import('~icons/custom/arrow-right')['default']
    ICustomCheck: typeof import('~icons/custom/check')['default']
    ICustomLogo: typeof import('~icons/custom/logo')['default']
    ICustomMinus: typeof import('~icons/custom/minus')['default']
    ICustomPanelLeft: typeof import('~icons/custom/panel-left')['default']
    ICustomPlay: typeof import('~icons/custom/play')['default']
    ICustomPlus: typeof import('~icons/custom/plus')['default']
    ICustomStepBack: typeof import('~icons/custom/step-back')['default']
    ICustomStepForward: typeof import('~icons/custom/step-forward')['default']
    Info: typeof import('./src/01_app/assets/icons/info.svg')['default']
    Logo: typeof import('./src/01_app/assets/icons/logo.svg')['default']
    Minus: typeof import('./src/01_app/assets/icons/minus.svg')['default']
    PanelLeft: typeof import('./src/01_app/assets/icons/panel-left.svg')['default']
    Play: typeof import('./src/01_app/assets/icons/play.svg')['default']
    Plus: typeof import('./src/01_app/assets/icons/plus.svg')['default']
    Projects: typeof import('./src/01_app/assets/icons/projects.svg')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/01_app/assets/icons/search.svg')['default']
    StepBack: typeof import('./src/01_app/assets/icons/step-back.svg')['default']
    StepForward: typeof import('./src/01_app/assets/icons/step-forward.svg')['default']
  }
}
