export const BACKPROP_STEPS = {
  EMPTY: 0,
  FORWARD_F11: 1,
  FORWARD_F12: 2,
  OUTPUT: 3,
  ERROR: 4,
  GRADIENT: 5,
  WEIGHT_UPDATE_W21: 6,
  WEIGHT_UPDATE_W22: 7,
  DELTA_1: 8,
  DELTA_2: 9,
  WEIGHT_UPDATE_W11: 10,
  WEIGHT_UPDATE_W12: 11,
  WEIGHT_UPDATE_W13: 12,
  WEIGHT_UPDATE_W14: 13,
} as const;
export const BACKWARD_TAB_STEP = BACKPROP_STEPS.GRADIENT;
export const LAST_STEP = Math.max(...Object.values(BACKPROP_STEPS));
